<a href="https://colab.research.google.com/github/abhay2255/LEARN.PY/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [1]:
#please provide your answer below this line.
import numpy as np
x = np.random.rand(3,3)
y = np.random.rand(3,3)
 
print(x)
print(y)
 
a=np.dot(x,y)
print(a)
a.transpose()

[[0.76085939 0.86632892 0.37553218]
 [0.06086621 0.4964655  0.68045423]
 [0.31166311 0.36597216 0.37991839]]
[[0.49267524 0.69573996 0.69322196]
 [0.98225236 0.63158341 0.77348843]
 [0.52582437 0.10714127 0.11950802]]
[[1.42327417 1.11675425 1.24241894]
 [0.8754411  0.42881117 0.50752385]
 [0.71279606 0.48868337 0.54453024]]


array([[1.42327417, 0.8754411 , 0.71279606],
       [1.11675425, 0.42881117, 0.48868337],
       [1.24241894, 0.50752385, 0.54453024]])

2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [2]:
#please provide your answer below this line.
import numpy as np
a=[[55,25,15], [30,44,2], [11,45,77]]
b=np.array(a)
print(b)
np.linalg.det(b)

[[55 25 15]
 [30 44  2]
 [11 45 77]]


137180.0000000001